config/routes.rb
Rails.application.routes.draw do
  devise_for :users, 
  controllers: {
   registrations: 'users/registrations' ,
   omniauth_callbacks: 'users/omniauth_callbacks'
   }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'articles#index'
  resources :articles do
    resources :comments, only: [:create, :destroy]
    # post "likes/:article_id/create"  => "likes#create"
    # delete "likes/:article_id/destroy"  => "likes#destroy"
    # post "likes/:article_id/topcreate"  => "likes#topcreate"
    # delete "likes/:article_id/topdestroy"  => "likes#topdestroy"

  end

  post "likes/:article_id/create"  => "likes#create"
  delete "likes/:article_id/destroy"  => "likes#destroy"
  post "likes/:article_id/topcreate"  => "likes#topcreate"
  delete "likes/:article_id/topdestroy"  => "likes#topdestroy"

  # post "likes/:article_id/create"  => "likes#create"
  # delete "likes/:article_id/destroy"  => "likes#destroy"

  # resources :likes, only: [:create]

  resources :users, only: [:index, :edit, :update, :show, :destroy] do
    get "likes" => "users#likes"
  end  

  resources :signup do
    collection do
      get 'entry_signup'
      get 'step1'
      get 'step2'
      get 'step3'# ここで、入力の全てが終了する
      get 'step4'
      get 'done' # 登録完了後のページ
    end
  end

  resources :categories do
    collection do
      get 'walk'  => 'categories#walk'
      get 'discipline'  => 'categories#discipline'
      get 'sick'  => 'categories#sick'
      get 'life'  => 'categories#life'
      get 'food'  => 'categories#food'
      get 'rearing'  => 'categories#rearing'
      get 'question'  => 'categories#question'
      get 'story'  => 'categories#story'
      get 'petloss'  => 'categories#petloss'
      get 'other'  => 'categories#other'
    end
  end  

  resources :genres do
    collection do
      get 'dog'  => 'genres#dog'
      get 'cat'  => 'genres#cat'
      get 'small_animal'  => 'genres#small_animal'
      get 'bird'  => 'genres#bird'
      get 'fish'  => 'genres#fish'
      get 'reptile'  => 'genres#reptile'
      get 'genre_other'  => 'genres#genre_other'
    end
  end  

  resources :details do
    collection do
      get 'latest'  => 'details#latest'
      get 'ranking'  => 'details#ranking'
      get 'search'  => 'details#search'
    end
  end
  


end

app/controllers/signup_controller.rb
class SignupController < ApplicationController
  before_action :validates_step1, only: :step2
  before_action :validates_step2, only: :step3
  before_action :validates_step3, only: :step4


  # 各アクションごとに新規インスタンスを作成し
  # 各アクションごとに、遷移元のページのデータをsessionに保管
  def step1
    @user = User.new # 新規インスタンス作成
  end

  def step2
    @profile = Profile.new # 新規インスタンスの作成
  end

  def step3
    @profile = Profile.new # 新規インスタンスを再度作成
  end

  def step4
    @user = User.new(
    name: session[:name], # sessionに保存された値をインスタンスに渡す
    email: session[:email],
    )
    
    @profile = Profile.new(
      avatar: session[:avatar], # sessionに保存された値をインスタンスに渡す
      self_introduction: session[:self_introduction],
      prefectures: session[:prefectures],
      city: session[:city],
      phone_number: session[:phone_number],
      birth_year: session[:birth_year],
      birth_month: session[:birth_month],
      birth_day: session[:birth_day],
      age: session[:age],
      gender: session[:gender],
      occupation: session[:occupation],
      expert: session[:expert],
      release: session[:release],
    )
  end

  def done
    sign_in User.find(session[:id]) unless user_signed_in?
  end

  # before_actionごとに、遷移元のページのデータをsessionに保管
  # 仮でインスタンスを作成しバリデーションチェックを行う
  def validates_step1
    # step1で入力された値をsessionに保存
    session[:name] = user_params[:name]
    session[:email] = user_params[:email]
    session[:password] = user_params[:password]
    session[:password_confirmation] = user_params[:password_confirmation]

    # バリデーション用に、仮でインスタンスを作成
    @user = User.new(
      name: session[:name], # sessionに保存された値をインスタンスに渡す
      email: session[:email],
      password: session[:password],
      password_confirmation: session[:password_confirmation],
    )
    # 仮で作成したインスタンスのバリデーションチェックを行う
    render '/signup/step1' unless @user.valid?(:validates_step1)
  
  end

  def validates_step2
    # step2で入力された値をsessionに保存
    # session[:phone_number] = user_params[:phone_number]
    # バリデーション用に、仮でインスタンスを作成する
    session[:phone_number] = profile_params[:phone_number]
    @profile = Profile.new(
      phone_number: session[:phone_number],
    )
    # 仮で作成したインスタンスのバリデーションチェックを行う
    render '/signup/step2' unless @profile.valid?(:validates_step2)
  end 

  def validates_step3
    session[:self_introduction] = profile_params[:self_introduction]
    session[:avatar] = profile_params[:avatar]
    session[:prefectures] = profile_params[:prefectures]
    session[:city] = profile_params[:city]
    session[:birth_year] = profile_params[:birth_year]
    session[:birth_month] = profile_params[:birth_month]
    session[:birth_day] = profile_params[:birth_day]
    session[:age] = profile_params[:age]
    session[:gender] = profile_params[:gender]
    session[:occupation] = profile_params[:occupation]
    session[:expert] = profile_params[:expert]
    session[:release] = profile_params[:release]

    # バリデーション用に、仮でインスタンスを作成する
    @profile = Profile.new(
      avatar: session[:avatar], # sessionに保存された値をインスタンスに渡す
      self_introduction: session[:self_introduction],
      prefectures: session[:prefectures],
      city: session[:city],
      birth_year: session[:birth_year],
      birth_month: session[:birth_month],
      birth_day: session[:birth_day],
      age: session[:age],
      gender: session[:gender],
      occupation: session[:occupation],
      expert: session[:expert],
      release: session[:release],
    )
    # 仮で作成したインスタンスのバリデーションチェックを行う
    render '/signup/step3' unless @profile.valid?(:validates_step3)
    
  end


  def create

    @user = User.new(
      name: session[:name], # sessionに保存された値をインスタンスに渡す
      email: session[:email],
      password: session[:password],
      password_confirmation: session[:password_confirmation],
    )
    
    if @user.save
      
      # ログインするための情報を保管
      session[:id] = @user.id

      @profile = Profile.new(
        user_id: @user.id,
        avatar: session[:avatar], # sessionに保存された値をインスタンスに渡す
        self_introduction: session[:self_introduction],
        prefectures: session[:prefectures],
        city: session[:city],
        phone_number: session[:phone_number],
        birth_year: session[:birth_year],
        birth_month: session[:birth_month],
        birth_day: session[:birth_day],
        age: session[:age],
        gender: session[:gender],
        occupation: session[:occupation],
        expert: session[:expert],
        release: session[:release],
      )
      @profile.save
      redirect_to done_signup_index_path
    else
      render '/signup/step4', notice: 'ユーザー登録が出来ませんでした'
    end
  end

  private
  # 許可するキーを設定
    def user_params
      params.require(:user).permit(
        :name, 
        :email,
        :password, 
        :password_confirmation, 
      )
  end

  def profile_params
    params.require(:profile).permit(
      :phone_number,
      :self_introduction,
      :avatar, 
      :prefectures, 
      :city, 
      :birth_year, 
      :birth_month, 
      :birth_day, 
      :age, 
      :gender, 
      :occupation, 
      :expert,
      :release 
    )
  end

end

app/helpers/signup_helper.rb
module SignupHelper
end

app/views/signup/_error-messages.html.haml
- if user.errors.any?
  - unless user.valid?(:validates_step1)
    - if errors = user.errors.full_messages_for(column.to_sym)
      %ul.has-error-text
        - errors.each do |error|
          %li=error

app/views/signup/_error-profile-messages.html.haml
- if profile.errors.any?
  - unless profile.valid?(:validates_step2)
    - if errors = profile.errors.full_messages_for(column.to_sym)
      %ul.has-error-text
        - errors.each do |error|
          %li=error

app/views/signup/_error-profile-messages2.html.haml
- if profile.errors.any?
  - unless profile.valid?(:validates_step3)
    - if errors = profile.errors.full_messages_for(column.to_sym)
      %ul.has-error-text
        - errors.each do |error|
          %li=error

app/views/signup/done.html.haml
#account-page.account-page.fadein
  .account-page__inner.clearfix
    %nav.progress
      %ul.progress-bar
        %li.through#through
          ユーザー情報
          .progress-status
          .progress-status_bar
        %li.active#through
          電話番号認証
          .progress-status
          .progress-status_bar
        %li.profile#through
          ユーザープロフィール
          .progress-status
          .progress-status_bar
        %li.confirm#through
          登録内容の確認
          .progress-status
          .progress-status_bar  
        %li.end#end#active
          完了
          .progress-status
          .progress-status_bar

    .account-page__inner__box.account-page__header
      %h2 新規登録
      %h5 新規アカウントの作成
      
    .account-page__inner__form.user-form
      .field
        .field-label-finishd
          ユーザー登録が完了しました。

      .field-entry.displayflex
        = link_to "TOPページへ", root_path, class: 'account-register-btn'

  .main-box-footer        

app/views/signup/entry_signup.html.haml
#account-page.account-page.fadein
  .account-page__inner.clearfix
    .account-page__inner__box.account-page__header
      %h2 新規登録
      %h5 新規アカウントの作成
      
    .account-page__inner__form.user-form
      = form_with model: @user, url: step2_signup_index_path, method: :get, local: true do |f|
        .field
          .field-label
            = link_to step1_signup_index_path, class: "btn-default" do
              = fa_icon 'envelope', width: "20", height: "20", class: "googlesai-icon"
              メールアドレスで登録する

        .field
          .field-label
            = link_to user_facebook_omniauth_authorize_path, class: "facebookrelative" do
              = fa_icon 'facebook', class: "facebook-icon"
              %span
                Facebookで登録する
        .field
          .field-label
            = link_to user_google_oauth2_omniauth_authorize_path, class: "google-login-icon" do
              .field-label-icon
                = image_tag 'googlelogo.png', width:"12", height: "12",class: "google-icon"
                %span
                  Googleで登録する

        .field-entry.displayflex
          .account-register-btn
            = link_to "ログイン画面へ", user_session_path, class: 'account-register-btn'

          .account-register-btn
            = link_to "新規登録画面へ", step1_signup_index_path, class: 'account-register-btn'
            %br/

  .main-box-footer          

app/views/signup/step1.html.haml
#account-page.account-page.fadein
  .account-page__inner.clearfix
    %nav.progress
      %ul.progress-bar
        %li.through#through#active
          ユーザー情報
          .progress-status
          .progress-status_bar
        %li.active
          電話番号認証
          .progress-status
          .progress-status_bar
        %li.profile
          ユーザープロフィール
          .progress-status
          .progress-status_bar
        %li.confirm
          登録内容の確認
          .progress-status
          .progress-status_bar  
        %li.end#end
          完了
          .progress-status
          .progress-status_bar
          

    .account-page__inner__box.account-page__header
      %h2 新規登録
      %h5 新規アカウントの作成
      
    .account-page__inner__form.user-form
      = form_with model: @user, url: step2_signup_index_path, method: :get, local: true do |f|
        .field
          .field-label
            = f.label :name, "ニックネーム"
            %i (10文字以内)
          .field-input
            = f.text_field :name, autofocus: true, placeholder: '名前を入力(必須)'
            =  render partial: 'error-messages', locals: {user: @user, column: "name"}
        
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email, placeholder: 'メールアドレスを入力（必須）'
            = render partial: 'error-messages', locals: {user: @user, column: "email"}
        
        .field
          .field-label
            = f.label :password
            %i (英数字6文字以上128文字以内)
          .field-input
            = f.password_field :password, placeholder: 'パスワードを入力'
            = render partial: 'error-messages', locals: {user: @user, column: "password"}
        
        .field
          .field-label
            = f.label :password_confirmation
          .field-input
            = f.password_field :password_confirmation, autocomplete: "off", placeholder: 'パスワードを入力（確認）'
            = render partial: 'error-messages', locals: {user: @user, column: "password_confirmation"}
        
        .field-entry.displayflex
          = f.submit "次へ進む", class: 'account-register-btn'
          = link_to "ログインへ戻る", user_session_path, class: 'account-register-btn'

          -# = render "devise/shared/links"

  .main-box-footer        

app/views/signup/step2.html.haml
#account-page.account-page.fadein
  .account-page__inner.clearfix
    %nav.progress
      %ul.progress-bar
        %li.through#through
          ユーザー情報
          .progress-status
          .progress-status_bar
        %li.active#active
          電話番号認証
          .progress-status
          .progress-status_bar
        %li.profile
          ユーザープロフィール
          .progress-status
          .progress-status_bar
        %li.confirm
          登録内容の確認
          .progress-status
          .progress-status_bar  
        %li.end#end
          完了
          .progress-status
          .progress-status_bar
          
    .account-page__inner__box.account-page__header
      %h2 新規登録
      %h5 新規アカウントの作成
      
    .account-page__inner__form.user-form
      = form_with model: @profile, url: step3_signup_index_path, method: :get, local: true do |f|
        .field
          .field-label
            = f.label :電話番号, class: "phone-number-register"
            %i (半角数字)

          .field-input
            = f.text_field :phone_number, autofocus: true, placeholder: '電話番号を入力(必須)'
            =  render partial: 'error-profile-messages', locals: {profile: @profile, column: "phone_number"}        

            %p 
              本人確認のため、携帯電話のSMS(ショートメッセージサービス)を利用して認証を行います。
              
        .field-entry.displayflex
          = f.submit "次へ進む", class: 'account-register-btn'
          = link_to "ログインへ戻る", user_session_path, class: 'account-register-btn'

  .main-box-footer        

app/views/signup/step3.html.haml
#account-page.account-page.fadein
  .account-page__inner.clearfix
    %nav.progress
      %ul.progress-bar
        %li.through#through
          ユーザー情報
          .progress-status
          .progress-status_bar
        %li.active#through
          電話番号認証
          .progress-status
          .progress-status_bar
        %li.profile#active
          ユーザープロフィール
          .progress-status
          .progress-status_bar
        %li.confirm
          登録内容の確認
          .progress-status
          .progress-status_bar  
        %li.end#end
          完了
          .progress-status
          .progress-status_bar

    .account-page__inner__box.account-page__header
      %h2 新規登録
      %h5 新規アカウントの作成
    .account-page__inner__form.user-form
      = form_with model: @profile, url: step4_signup_index_path, method: :get, local: true do |f|
        .field
          .field-label
            = f.label :avatar, "アバター画像"
            %i （任意）
          .field-input
            = f.file_field :avatar, autofocus: true, placeholder: '画像を選択(任意)'
            =  render partial: 'error-profile-messages2', locals: {profile: @profile, column: "avatar"} 
        .field
          .field-label
            = f.label :自己紹介
            %i (任意：300文字以内)
          .field-input
            = f.text_area :self_introduction, placeholder: '自己紹介を入力（任意）', rows: 4, class: "self-introduction-register"
            =  render partial: 'error-profile-messages2', locals: {profile: @profile, column: "self_introduction"} 
        
        .new-article-select-heading-box
          .new-article-select-box-heading
            詳細なプロフィール
        .field
          .field-label
            = f.label :お住まいの都道府県
            %i (選択任意)
          .field-input
            = f.collection_select :prefectures, Prefecture.all, :id, :name, {prompt: "▼"},{class:"select-area-default"}
            = render partial: 'error-profile-messages2', locals: {profile: @profile, column: "prefectures"}     
        .field
          .field-label
            = f.label :市区町村
            %i (任意)
          .field-input
            = f.text_field :city, placeholder: '市町村名を入力（任意）'
            = render partial: 'error-profile-messages2', locals: {profile: @profile, column: "city"}
        .field
          .field-label
            = f.label :生年月日
            %i (任意)
        .field-birthday-register.displayflex  
          .field-label-register
            = f.label :年
            .field-input-register
              = f.text_field :birth_year, placeholder: '年を入力'
              = render partial: 'error-profile-messages2', locals: {profile: @profile, column: "birth_year"}
          .field-label-register
            = f.label :月
            .field-input-register
              = f.text_field :birth_month, placeholder: '月を入力'
              = render partial: 'error-profile-messages2', locals: {profile: @profile, column: "birth_month"}
          .field-label-register
            = f.label :日            
            .field-input-register
              = f.text_field :birth_day, placeholder: '日を入力'
              = render partial: 'error-profile-messages2', locals: {profile: @profile, column: "birth_day"}
          
        .field
          .field-label.require-register
            = f.label :年代、性別
            %i (必須)
        .field.displayflex
          .field-label-register.half-box.require-register
            = f.label :年代
          .field-input-register.half-box.require-register
            = f.select :age, Profile.ages.keys.to_a ,{prompt: "---"},{class:"select-area-default"}
            = render partial: 'error-profile-messages2', locals: {profile: @profile, column: "age"}
          .field-label-register.half-box.require-register
            = f.label :性別
          .field-input-register.half-box.require-register
            = f.select :gender, Profile.genders.keys.to_a ,{prompt: "---"},{class:"select-area-default"}
            = render partial: 'error-profile-messages2', locals: {profile: @profile, column: "gender"}

        .field
          .field-label
            = f.label :職業
            %i (任意)
          .field-input
            = f.text_field :ocupation, placeholder: '職業を入力'
            = render partial: 'error-profile-messages2', locals: {profile: @profile, column: "ocupation"}
        
        .new-article-select-heading-box
          .new-article-select-box-heading
            当てはまる方のみチェックして下さい
        .field.displayflex
          .field-label-register.half-box
            = f.label :専門家ですか？
            %i 
          .field-label-register.half-box
            = f.check_box :expert, id: :expert_checkbox,:as => :boolean
            = render partial: 'error-profile-messages2', locals: {profile: @profile, column: "expert"}
        .field.displayflex
          .field-label-register.half-box
            = f.label :詳細なプロフィールを公開しますか？
          .field-label-register.half-box
            = f.check_box :release, id: :expert_checkbox,:as => :boolean
            = render partial: 'error-profile-messages2', locals: {profile: @profile, column: "release"}
        

        .field-entry.displayflex
          = f.submit "登録内容を確認する", class: 'account-register-btn'
          = link_to "ログインへ戻る", user_session_path, class: 'account-register-btn'

          -# = render "devise/shared/links"

  .main-box-footer        

app/views/signup/step4.html.haml
#account-page.account-page.fadein
  .account-page__inner.clearfix
    %nav.progress
      %ul.progress-bar
        %li.through#through
          ユーザー情報
          .progress-status
          .progress-status_bar
        %li.active#through
          電話番号認証
          .progress-status
          .progress-status_bar
        %li.profile#addres#through
          ユーザープロフィール
          .progress-status
          .progress-status_bar
        %li.confirm#payment#active
          登録内容の確認
          .progress-status
          .progress-status_bar  
        %li.end#end
          完了
          .progress-status
          .progress-status_bar
    .account-page__inner__box.account-page__header
      %h2 新規登録
      %h5 新規アカウントの作成
    .account-page__inner__form.user-form
      = form_with model: @profile, url: signup_index_path, method: :post, local: true do |f|
        .field
          .field-label
            ニックネーム:
            = @user.name
        .field
          .field-label
            Eメール:
            = @user.email
        .field
          .field-label
            自己紹介
          .field-label  
            = @profile.self_introduction
        .field
          .field-label
            電話番号:
            = @profile.phone_number
        .field
          .field-label
            都道府県:
          - if @profile.prefectures.present? 
            = Prefecture.find(@profile.prefectures).name
        .field
          .field-label
            生年月日:
            = @profile.birth_year
            年
            = @profile.birth_month
            月
            = @profile.birth_day
            日
        .field
          .field-label
            年代:
            = @profile.age
        .field
          .field-label
            性別:
            = @profile.gender
        .field
          .field-label
            職業:
            = @profile.occupation
        .field
          .field-label
          - if @profile.expert == true
            職業:
            専門家です  
        .field
          .field-label
          - if @profile.release == true
            詳細なプロフィールを公開します
          - elsif @profile.release == false
            詳細なプロフィールを公開しません

        .field-entry.displayflex
          = f.submit "登録を完了する", class: 'account-register-btn'
          = link_to "ログインへ戻る", user_session_path, class: 'account-register-btn'