config/routes.rb
Rails.application.routes.draw do
  devise_for :users, 
  controllers: {
   registrations: 'users/registrations' ,
   omniauth_callbacks: 'users/omniauth_callbacks'
   }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'articles#index'
  resources :articles do
    resources :comments, only: [:create, :destroy]
    # post "likes/:article_id/create"  => "likes#create"
    # delete "likes/:article_id/destroy"  => "likes#destroy"
    # post "likes/:article_id/topcreate"  => "likes#topcreate"
    # delete "likes/:article_id/topdestroy"  => "likes#topdestroy"

  end

  post "likes/:article_id/create"  => "likes#create"
  delete "likes/:article_id/destroy"  => "likes#destroy"
  post "likes/:article_id/topcreate"  => "likes#topcreate"
  delete "likes/:article_id/topdestroy"  => "likes#topdestroy"

  # post "likes/:article_id/create"  => "likes#create"
  # delete "likes/:article_id/destroy"  => "likes#destroy"

  # resources :likes, only: [:create]

  resources :users, only: [:index, :edit, :update, :show, :destroy] do
    get "likes" => "users#likes"
  end  

  resources :signup do
    collection do
      get 'entry_signup'
      get 'step1'
      get 'step2'
      get 'step3'# ここで、入力の全てが終了する
      get 'step4'
      get 'done' # 登録完了後のページ
    end
  end

  resources :categories do
    collection do
      get 'walk'  => 'categories#walk'
      get 'discipline'  => 'categories#discipline'
      get 'sick'  => 'categories#sick'
      get 'life'  => 'categories#life'
      get 'food'  => 'categories#food'
      get 'rearing'  => 'categories#rearing'
      get 'question'  => 'categories#question'
      get 'story'  => 'categories#story'
      get 'petloss'  => 'categories#petloss'
      get 'other'  => 'categories#other'
    end
  end  

  resources :genres do
    collection do
      get 'dog'  => 'genres#dog'
      get 'cat'  => 'genres#cat'
      get 'small_animal'  => 'genres#small_animal'
      get 'bird'  => 'genres#bird'
      get 'fish'  => 'genres#fish'
      get 'reptile'  => 'genres#reptile'
      get 'genre_other'  => 'genres#genre_other'
    end
  end  

  resources :details do
    collection do
      get 'latest'  => 'details#latest'
      get 'ranking'  => 'details#ranking'
      get 'search'  => 'details#search'
    end
  end
  


end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user, optional: true
  has_many :comments, dependent: :destroy
  has_many :images, dependent: :destroy
  belongs_to :category
  belongs_to :genre
  # has_many :stocks, dependent: :destroy  
  has_many :likes, dependent: :destroy    
  
  accepts_nested_attributes_for :images, allow_destroy: true
  validates  :title,  presence: true, length:{minimum: 1,maximum: 40}
  validates :content, presence: true, length:{minimum: 1,maximum: 1000}
  validates :category_id, presence: {message:  "を選択して下さい"}
  validates :genre_id, presence: {message:  "を選択して下さい"}
  

  def self.create_ranks #Articleクラスからデータを取ってくる処理なのでクラスメソッド
    Article.find(Like.group(:article_id).order('count(article_id) desc').limit(10).pluck(:article_id))
  end

  def self.create_all_ranks #Articleクラスからデータを取ってくる処理なのでクラスメソッド
    Article.find(Like.group(:article_id).order('count(article_id) desc').pluck(:article_id))
  end



  

  # def reject_both_blank(attributes)
    # if attributes[:id]
    #   attributes.merge!(_destroy: "1") if attributes[:url].blank? and attributes[:flip].blank?
    #   !attributes[:face].blank? and attributes[:flip].blank?
    # else
    #   attributes[:face].blank? and attributes[:flip].blank?
    # end
  # end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :move_to_index, except: [:index,:create, :show]



  def index
    # 記事を３件づつ最新順に取得
    @articles = Article.includes(:user).page(params[:page]).per(3).order("created_at DESC")


    # カテゴリごとに記事を３件づつ最新順に取得
    @articles_walk = Article.where(:category_id => 1).includes(:user).page(params[:page]).per(3).order("created_at DESC")
    @articles_discipline = Article.where(:category_id => 2).includes(:user).page(params[:page]).per(3).order("created_at DESC")
    @articles_sick= Article.where(:category_id => 3).includes(:user).page(params[:page]).per(3).order("created_at DESC")
    @articles_life= Article.where(:category_id => 4).includes(:user).page(params[:page]).per(3).order("created_at DESC")
    @articles_food= Article.where(:category_id => 5).includes(:user).page(params[:page]).per(3).order("created_at DESC")
    @articles_rearing= Article.where(:category_id => 6).includes(:user).page(params[:page]).per(3).order("created_at DESC")
    @articles_question= Article.where(:category_id => 7).includes(:user).page(params[:page]).per(3).order("created_at DESC")
    @articles_story= Article.where(:category_id => 8).includes(:user).page(params[:page]).per(3).order("created_at DESC")
    @articles_petloss= Article.where(:category_id => 9).includes(:user).page(params[:page]).per(3).order("created_at DESC")
    @articles_other= Article.where(:category_id => 10).includes(:user).page(params[:page]).per(3).order("created_at DESC")
    
    # ジャンルごとに記事を３件づつ最新順に取得
    @articles_dog = Article.where(:genre_id => 1).includes(:user).page(params[:page]).per(3).order("created_at DESC")
    @articles_cat = Article.where(:genre_id => 2).includes(:user).page(params[:page]).per(3).order("created_at DESC")
    @articles_small_animal = Article.where(:genre_id => 3).includes(:user).page(params[:page]).per(3).order("created_at DESC")
    @articles_bird = Article.where(:genre_id => 4).includes(:user).page(params[:page]).per(3).order("created_at DESC")
    @articles_fish = Article.where(:genre_id => 5).includes(:user).page(params[:page]).per(3).order("created_at DESC")
    @articles_reptile = Article.where(:genre_id => 6).includes(:user).page(params[:page]).per(3).order("created_at DESC")
    @articles_genre_other = Article.where(:genre_id => 7).includes(:user).page(params[:page]).per(3).order("created_at DESC")
  end

  def new
    redirect_to new_user_session_path unless user_signed_in?
    @article = Article.new
    @article.images.build
    gon.length = 0
  end

  def create
    @article = Article.new(article_params)
    if @article.save && params[:images].present? 
      params[:images][:url].each do |url|
      @article.images.create(url: url, article_id: @article.id)
      end

    elsif @article.save

    else
      @article.images.build
      render action: :new
    end
  end

  def destroy
    article = Article.find(params[:id])
    if user_signed_in? && article.user_id == current_user.id
      article.destroy
      redirect_to root_path, notice: '記事を削除しました'
    else
      render :show
    end
  end

  def edit
    @article = Article.find(params[:id])
    if  user_signed_in? && @article.user_id == current_user.id
      @length = @article.images.length 
      @filefield_length = 5 - @article.images.length 
      @index = -1
      gon.length = @article.images.length
      if @length == 0 
        @article.images.build
      end  
    else
      redirect_to root_path unless @article.user_id == current_user.id
    end
  end

  def update
   @article = Article.find(params[:id])
    if @article.user_id == current_user.id
      if params[:images].present? 
        params[:images][:url].each do |url|
        @article.images.create(url: url, article_id: @article.id) 
        end

        @article.update(article_params) 

      else 
        @article.update(article_params) 

      end  
    else  
      redirect_to action: 'edit'  
    end
  end
  
  def show
    @article = Article.find(params[:id])
    @likes_count = Like.where(article_id: @article.id).count
    if @article.present? 
      @user_article = Article.where(user_id: @article.user.id).where.not(id: @article.id).limit(16).order("created_at DESC")
      @comment_article = Comment.where(article_id: @article.id).limit(5).order("created_at DESC")
      @comment = Comment.new
      @comment_all = Comment.where(article_id: @article.id).order("created_at DESC")
    else 
      respond_to do |format|
        format.html { redirect_to root_path }
        format.json
      end  
    end  
  end


  private

  def article_params
    params.require(:article).permit(:title, :content, :category_id, :genre_id, images_attributes: [:url, :id, :_destroy]).merge(user_id: current_user.id)
  end

  def move_to_index
    redirect_to redirect_to root_path unless user_signed_in?
  end



end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.haml
.article-post-index{data:{id: "#{article.id}"}}  
  .article-post.fadein.displayflex
    .article-post-content
      = link_to article_path(article) do
        .article-post-content-clickarea
          .article-post__title
            = article.title
          .article-post__text  
            = article.content
      .users-resource-select.displayflex
        .users-resource-select__name  
          = fa_icon 'user', class: 'content-user__icon'
          = article.user.name
        .users-resource-select__like
        - if user_signed_in?
          - if Like.find_by(user_id: current_user.id, article_id: article.id) 
            = link_to "/likes/#{article.id}/topdestroy",{method: "delete"}, class: "liked-btn" do
              .users-resource-select__like__box{data: {id: article.id}}
                = fa_icon 'heart', class: 'liked-btn__icon change-pink'
          - else  
            = link_to "/likes/#{article.id}/topcreate",{method: "post"}, class: "like-btn" do
              .users-resource-select__like__box{data: {id: article.id}}
                = fa_icon 'heart', class: 'like-btn__icon change-gray'
        - else
        .article-post-show-like-icon
          = Like.where(article_id: article.id).count       
        .article-post-show-like-heading
          いいね！
        .users-post-time-index
          投稿日時：
          = article.created_at.to_s    
        - if user_signed_in? && current_user.id == article.user_id
          .users-resource-select__edit
            = fa_icon 'edit', class: 'content-user__icon'
            = link_to '編集', edit_article_path(article), method: :get
          .users-resource-select__delete
            = fa_icon 'trash', class: 'content-user__icon'
            = link_to '削除', article_path(article), method: :delete  

    .article-post__image  
      = image_tag "#{article.images.first.url}", class: 'article-post__image' if article.images.present?


  

  



  

app/views/articles/_error-messages.html.haml
- if article.errors.any?
  - unless article.valid?
    - if errors = article.errors.full_messages_for(column.to_sym)
      %ul.has-error-text
        - errors.each do |error|
          %li=error

app/views/articles/_header-btn.html.haml
.header-low
  .header-low__row
    .left-header-low-btn.displayflex
      .main-contents-categories.displayflex
        %li.main-contents-categories__genres.header-hover-btn
          = fa_icon 'paw', class: 'header-btn__icon'
          = link_to "#100" do
            ジャンル
            %ul#header-genre__list
              .parents__list
                - @genres.each do |genre|
                  = link_to "##{genre.id}" do
                    %li.parents__list-box
                      #{genre.name}

        %li.main-contents-categories__categories.header-hover-btn
          = fa_icon 'paw', class: 'header-btn__icon'
          = link_to "#101" do
            カテゴリ
          %ul#header-genre__list
            .parents__list
              - @categories.each do |category|
                = link_to "##{category.id + 30}" do
                  %li.parents__list-box
                    #{category.name}          
        .main-contents-categories__ranking
          =link_to ranking_details_path do
            = fa_icon 'paw', class: 'header-btn__icon'
            ランキング
        .main-contents-categories__lost_child
          = fa_icon 'paw', class: 'header-btn__icon'
          カレンダー
      .main-contents-other.displayflex
        -# .main-contents-other__follow
        -#   = fa_icon 'leaf', class: 'header-btn__icon'
        -#   フォロー
        .main-contents-other__myitem
          = fa_icon 'star', class: 'header-btn__icon'
          マイアイテム
        .main-contents-other__detailed-search
          = fa_icon 'search-plus', class: 'header-btn__icon'
          詳細検索
        .main-contents-other__order 
          キャンバス  
          = fa_icon 'comment', class: 'header-btn__icon'
            




        

app/views/articles/_index-category.html.haml
.index-render-container#101
  .index-render-box-category-walk.index-render-box-lightgreen#31
    = link_to walk_categories_path(@articles_walk) do
      %p4 カテゴリ：散歩・おでかけ
      = render partial: 'articles/article', collection: @articles_walk
    = link_to walk_categories_path(@articles_walk) do
      .category-show
        もっと見る
  .index-render-box-category-discipline.index-render-box-green#32
    = link_to discipline_categories_path(@articles_discipline) do            
      %p4 カテゴリ：しつけ
      = render partial: 'articles/article', collection: @articles_discipline
    = link_to discipline_categories_path(@articles_discipline) do
      .category-show
        もっと見る          
  .index-render-box-category-sick.index-render-box-lightgreen#33
    = link_to sick_categories_path(@articles_sick) do
      %p4 カテゴリ：怪我・病気・予防・介護
      = render partial: 'articles/article', collection: @articles_sick
    = link_to sick_categories_path(@articles_sick) do
      .category-show
        もっと見る          
  .index-render-box-category-life.index-render-box-green#34
    = link_to life_categories_path(@articles_life) do
      %p4 カテゴリ：くらし・生活・日常
      = render partial: 'articles/article', collection: @articles_life
    = link_to life_categories_path(@articles_life) do
      .category-show
        もっと見る          
  .index-render-box-category-food.index-render-box-lightgreen#35
    = link_to food_categories_path(@articles_food) do
      %p4 カテゴリ：エサ・食事
      = render partial: 'articles/article', collection: @articles_food  
    = link_to food_categories_path(@articles_food) do
      .category-show
        もっと見る    
  .index-render-box-category-rearing.index-render-box-green#36
    = link_to rearing_categories_path(@articles_rearing) do
      %p4 カテゴリ：ケア・飼育方法
      = render partial: 'articles/article', collection: @articles_rearing  
    = link_to rearing_categories_path(@articles_rearing) do
      .category-show
        もっと見る           
  .index-render-box-category-question.index-render-box-lightgreen#37
    = link_to question_categories_path(@articles_question) do
      %p4 カテゴリ：Q & A
      = render partial: 'articles/article', collection: @articles_question
    = link_to question_categories_path(@articles_question) do
      .category-show
        もっと見る           
  .index-render-box-category-success-failure-story.index-render-box-green#38
    = link_to  story_categories_path(@articles_story) do
      %p4 カテゴリ：成功談・失敗談
      = render partial: 'articles/article', collection: @articles_story
    = link_to  story_categories_path(@articles_story) do
      .category-show
        もっと見る           
  .index-render-box-category-petloss.index-render-box-lightgreen#39
    = link_to petloss_categories_path(@articles_petloss) do
      %p4 カテゴリ：迷子
      = render partial: 'articles/article', collection: @articles_petloss
    = link_to petloss_categories_path(@articles_petloss) do
      .category-show
        もっと見る
  .index-render-box-category-other.index-render-box-green#40
    = link_to other_categories_path(@articles_other) do
      %p4 カテゴリ：その他
      = render partial: 'articles/article', collection: @articles_other 
    = link_to other_categories_path(@articles_other) do
      .category-show
        もっと見る            

app/views/articles/_index-genre.html.haml
.index-render-container#100
  .index-render-box-genre-dog.index-render-box-green#1
    = link_to dog_genres_path(@articles) do        
      %p4 ジャンル：犬
      = render partial: 'articles/article', collection: @articles_dog 
    = link_to dog_genres_path(@articles) do
      .category-show
        もっと見る
  .index-render-box-genre-cat.index-render-box-lightgreen#2
    = link_to cat_genres_path(@articles_cat) do
      %p4 ジャンル：猫
      = render partial: 'articles/article', collection: @articles_cat
    = link_to cat_genres_path(@articles_cat) do
      .category-show
        もっと見る
  .index-render-box-genre-small-animal.index-render-box-green#3
    = link_to small_animal_genres_path(@articles_small_animal) do          
      %p4 ジャンル：小動物
      = render partial: 'articles/article', collection: @articles_small_animal
    = link_to small_animal_genres_path(@articles_small_animal) do
      .category-show
        もっと見る
  .index-render-box-genre-bird.index-render-box-lightgreen#4
    = link_to bird_genres_path(@articles_bird) do
      %p4 ジャンル：とり
      = render partial: 'articles/article', collection: @articles_bird
    = link_to bird_genres_path(@articles_bird) do
      .category-show
        もっと見る
  .index-render-box-genre-fish.index-render-box-green#5
    = link_to fish_genres_path(@articles_fish) do
      %p4 ジャンル：さかな
      = render partial: 'articles/article', collection:@articles_fish
    = link_to fish_genres_path(@articles_fish) do
      .category-show
        もっと見る
  .index-render-box-genre-reptile.index-render-box-lightgreen#6
    = link_to reptile_genres_path(@articles_reptile) do
      %p4 ジャンル：爬虫類
      = render partial: 'articles/article', collection: @articles_reptile
    = link_to reptile_genres_path(@articles_reptile) do
      .category-show
        もっと見る                 
  .index-render-box-genre-other.index-render-box-green#7
    = link_to genre_other_genres_path(@articles_genre_other) do
      %p4 ジャンル：その他
      = render partial: 'articles/article', collection: @articles_genre_other
    = link_to genre_other_genres_path(@articles_genre_other) do
      .category-show
        もっと見る

app/views/articles/_top-render.html.haml
- if @search_articles
  .index-render-container
    .index-render
      .index-render-box-search
        %p4 検索結果
        - if @search_articles.length >= 1  
          .search-result-heading-box
            = params[:q][:title_or_content_cont_all]
            の検索結果　新着１０件
          = render partial: 'articles/article', collection: @search_articles
          .result-show
            .show-all-result-btn
              全件表示する
            .show-all-result-off-btn
              非表示にする
          .show-all-result-display-off
            = render partial: 'articles/article', collection: @search_articles_all

        - elsif @search_articles.length == 0
          .index-render-box-search            
            %h4 該当する記事が見つかりませんでした。
  .index-render-container
    .index-render-box
      %p4 新着記事
      = render partial: 'articles/article', collection: @articles
    = link_to latest_details_path(@articles) do
      .category-show
        もっと見る
- else
  .index-render-container
    .index-render    
      .index-render-box
      = link_to latest_details_path(@articles) do
        %p4 新着記事
        = render partial: 'articles/article', collection: @articles
      = link_to latest_details_path(@articles) do
        .category-show
          もっと見る            

    = render 'articles/index-genre' 
    = render 'articles/index-category' 

app/views/articles/create.html.haml
.contents-box.fadein
  .success
    .success__box
      .success-btn-text
        投稿が完了しました。
      %a.success-btn-link{:href => "/articles"} 投稿一覧へ戻る
  .main-box-footer-conplete     

app/views/articles/destroy.html.haml
.contents-box.fadein
  .success
    .success__box
      .success-btn-text
        削除が完了しました。
      %a.success-btn-link{:href => "/"} 投稿一覧へ戻る
  .main-box-footer-conplete     

app/views/articles/edit.html.haml
.contents-box.fadein
  = form_with model: @article, local: true, multiple: true, html: {class: "new__form"}  do |f|
    .article-post-main-view
      %h3
      .file-form-box 
        .dropzone-container-edit.displayflex
          #preview-image  
          = f.fields_for :images, @article.images do |pic|
            .dropzone-preview-edit
              .img_box-container       
                .img_box
                  -  if @length >=1
                    = image_tag "#{pic.object.url.thumb.url}", class: "article-edit-img"
                    .img_box_delete-heading
                      削除画像をチェック
                    .img_box_delete
                      削除する: 
                      = pic.check_box :_destroy
                  -  if @length == 0    
                    .article-edit-img-empty
                  -# = link_to '削除',pic.object, method: :delete, data: { confirm: "写真を削除します"}
                  -# - @article.images.each do |picture|
              .dropzone-area-edit
                = pic.label :url, class: 'dropzone-area__label', for: "input-box-image"  do
                  .input-area-container.displayflex 
                    .input_area
                      = pic.file_field :url, multiple: true, name: 'images[url][]', class: 'input-box-image input-box-image-edit', id: 'input-box-image', 'data-image': 0                
                    .choice_area
                      .choice_area__heading
                        追加画像を選択
                        %br 最大５枚
                      .choice_area__text
                        画像を
                        %br 選択して下さい
        .new-article
          .input-box-title
            = f.label :title, class: 'input-box-title', for: "input-box-title"  do
              = f.text_field :title, class: "input-box-title", placeholder:"タイトル（必須40文字まで）",id: "input-box-title", rows: 1
          .input-box-text  
            = f.label :content, class: 'input-box-text', for: "input-box-text" do         
              = f.text_area :content, class: "input-box-text", placeholder:"テキスト（必須1000文字まで）",id: "input-box-text", rows: 5
        .new-article-select-heading-box
          .new-article-select-box-heading
            選択必須
        .new-article-select-box
          .input-box-select.displayflex
            .input-box-select-container
              .new-article-select-box-heading
                ジャンル
              = f.collection_select(:genre_id, @genres, :id, :name,{prompt: "--------"}, class: "input-box-select-area") 
              .clearfix
                =  render partial: 'error-messages', locals: {article: @article, column: "genre_id"}
                        
            .input-box-select-container
              .new-article-select-box-heading.displayflex
                カテゴリ 
              = f.collection_select(:category_id, @categories, :id, :name,{prompt: "--------"}, class: "input-box-select-area") 
              .clearfix
                =  render partial: 'error-messages', locals: {article: @article, column: "genre_id"}
            

      .input-box-image__del
        = f.submit '編集する', class: 'form__edit'
    .main-box-footer-edit

app/views/articles/index.html.haml
.header-select-btn
  = render 'articles/header-btn' 

.main-index-box.displayflex
  .main-contents.fadein
    .articles-box-search
      = render 'top-render' 

  .side-bar
    = render 'shared/side-bar'   

app/views/articles/new.html.haml
.contents-box.fadein
  = form_with model: @article, local: true, multiple: true do |f|
    .dropzone-container-heading
      選択任意
    .dropzone-container
      .dropzone-preview.displayflex
        = f.fields_for :images do |g|  
          #preview-image
          .dropzone-area  
            = g.label :url, class: 'dropzone-area__label', for: "input-box-image"  do
              .input_area
                = g.file_field :url, multiple: true, name: 'images[url][]', class: 'input-box-image', id: 'input-box-image', 'data-image': 0   
                %p.text
                  画像を
                  %br 選択して下さい                 
    .new-article
      .new-articlecontainer-heading
        入力必須
      .input-box-title
        = f.label :title, class: 'input-box-title', for: "input-box-title-area"  do
          = f.text_field :title, class: "input-box-title-area", placeholder:"タイトル（必須40文字まで）",id: "input-box-title-area", value: '', rows: 1
      
      .clearfix
      =  render partial: 'error-messages', locals: {article: @article, column: "title"}
    
      .input-box-text  
        = f.label :content, class: 'input-box-text', for: "input-box-text-area" do         
          = f.text_area :content, class: "input-box-text-area", placeholder:"テキスト（必須1000文字まで）",id: "input-box-text-area", value: '', rows: 5
    
      .clearfix
      =  render partial: 'error-messages', locals: {article: @article, column: "content"}
    
    
    .new-article-select-heading-box
      .new-article-select-box-heading
        選択必須
    .new-article-select-box
      .input-box-select.displayflex
        .input-box-select-container
          .new-article-select-box-heading
            ジャンル
          = f.collection_select(:genre_id, @genres, :id, :name,{prompt: "--------"}, class: "input-box-select-area") 
          .clearfix
            =  render partial: 'error-messages', locals: {article: @article, column: "genre_id"}
        
        .input-box-select-container
          .new-article-select-box-heading.displayflex
            カテゴリ 
          = f.collection_select(:category_id, @categories, :id, :name,{prompt: "--------"}, class: "input-box-select-area") 
          .clearfix
            =  render partial: 'error-messages', locals: {article: @article, column: "category_id"}
            



      
      -#   = f.label :category, 'カテゴリ' 
      -#     = f.collection_select :category_id, Category.all, :id, :name,{prompt: "---"}
            

    .input-box-image__del
      = f.submit '投稿する', class: 'form__contribute' 
    
  .main-box-footer-new

app/views/articles/show.html.haml
.contents-box.fadein
  .article-post-main-view
    -  if @article.images.present? 
      .article-post-photo__high
        = image_tag "#{@article.images.first.url}", class: 'image', class:".article-post-photo__high__image",id:"mainimage", width: "300px", height: "300px"
        .more
        %ul.more_list
    .article-post-photo__low.displayflex
      - @article.images.each do |image| 
        .product-exhibit-photo__low__image
          .product-exhibit-photo__low__image__1
            = image_tag "#{ image.url}", width: "60px", height: "60px",class:"details__image__low__image"


    .article-post-main-title    
      = @article.title
    .article-post-main-text   
      = @article.content
      .article-post-main-info.user-sourse-btn.displayflex
        .article-post-show-contributer
          = fa_icon 'user', class: 'content-user__icon'
        %p
          投稿者
        .article-post-show-user    
          = @article.user.name

        .article-post-show-like-icon
        - if user_signed_in?
          - if Like.find_by(user_id: current_user.id, article_id: @article.id) 
            = link_to "/likes/#{@article.id}/destroy",{method: "delete"}, class: "liked-btn" do
              .users-resource-select__like__box{data: {id: @article.id}}
                = fa_icon 'heart', class: 'liked-btn__icon'
          - else  
            = link_to "/likes/#{@article.id}/create",{method: "post"}, class: "liked-btn" do
              .users-resource-select__like__box{data: {id: @article.id}}
                = fa_icon 'heart', class: 'like-btn__icon'
        - else
        .article-post-show-like-icon
          = @likes_count        
        .article-post-show-like-heading
          いいね！
        .article-post-show-contribute-time 
          = @article.created_at.to_s 
    .show-article-select-box
      .show-article-select-box-container   
        .input-box-select-show.displayflex
          .input-box-select-chose.displayflex
            ジャンル：
            = @article.genre.name 
          .input-box-select-chose.displayflex
            カテゴリ：
            = @article.category.name  
    -if user_signed_in? && @article.user_id == current_user.id            
      .show-article-edit-box
        .new-article-edit-box   
          .input-box-edit-show
            .input-box-edit-container
              .input-box-edit-container__edit
                = link_to '記事を編集する', edit_article_path(@article), method: :get,class: "input-box-edit-container__edit__btn"
              .input-box-edit-container__delete
                = link_to '記事を削除する', article_path(@article), method: :delete,class: "input-box-edit-container__delet__btn"


  = render 'comments/comment'

  .users-other-article
    = fa_icon 'user', class: 'content-main__icon'
    = "#{@article.user.name}さんのその他の記事"
  .article-show-user-contributed.displayflex
    - @user_article.each do |user_article|
      .article-show-user-contributed-container
        = link_to article_path(user_article) do
          .article-show-user-contributed-main-box
            .contributed-box
              .contributed-main-image
                -  if user_article.images.present?
                  = image_tag "#{user_article.images.first.url}", class: 'contributed-image', width: "100%", height: "150px"
                  .more
                  %ul.more_list
              .article-post-main-title    
                = user_article.title
              .article-post-main-text   
                = user_article.content  


      

app/views/articles/update.html.haml
.contents-box.fadein
  .success
    .success__box
      .success-btn-text
        編集が完了しました。
      %a.success-btn-link{:href => "/"} 投稿一覧へ戻る
  .main-box-footer-conplete      