config/routes.rb
Rails.application.routes.draw do
  devise_for :users, 
  controllers: {
   registrations: 'users/registrations' ,
   omniauth_callbacks: 'users/omniauth_callbacks'
   }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'articles#index'
  resources :articles do
    resources :comments, only: [:create, :destroy]
    # post "likes/:article_id/create"  => "likes#create"
    # delete "likes/:article_id/destroy"  => "likes#destroy"
    # post "likes/:article_id/topcreate"  => "likes#topcreate"
    # delete "likes/:article_id/topdestroy"  => "likes#topdestroy"

  end

  post "likes/:article_id/create"  => "likes#create"
  delete "likes/:article_id/destroy"  => "likes#destroy"
  post "likes/:article_id/topcreate"  => "likes#topcreate"
  delete "likes/:article_id/topdestroy"  => "likes#topdestroy"

  # post "likes/:article_id/create"  => "likes#create"
  # delete "likes/:article_id/destroy"  => "likes#destroy"

  # resources :likes, only: [:create]

  resources :users, only: [:index, :edit, :update, :show, :destroy] do
    get "likes" => "users#likes"
  end  

  resources :signup do
    collection do
      get 'entry_signup'
      get 'step1'
      get 'step2'
      get 'step3'# ここで、入力の全てが終了する
      get 'step4'
      get 'done' # 登録完了後のページ
    end
  end

  resources :categories do
    collection do
      get 'walk'  => 'categories#walk'
      get 'discipline'  => 'categories#discipline'
      get 'sick'  => 'categories#sick'
      get 'life'  => 'categories#life'
      get 'food'  => 'categories#food'
      get 'rearing'  => 'categories#rearing'
      get 'question'  => 'categories#question'
      get 'story'  => 'categories#story'
      get 'petloss'  => 'categories#petloss'
      get 'other'  => 'categories#other'
    end
  end  

  resources :genres do
    collection do
      get 'dog'  => 'genres#dog'
      get 'cat'  => 'genres#cat'
      get 'small_animal'  => 'genres#small_animal'
      get 'bird'  => 'genres#bird'
      get 'fish'  => 'genres#fish'
      get 'reptile'  => 'genres#reptile'
      get 'genre_other'  => 'genres#genre_other'
    end
  end  

  resources :details do
    collection do
      get 'latest'  => 'details#latest'
      get 'ranking'  => 'details#ranking'
      get 'search'  => 'details#search'
    end
  end
  


end

app/views/layouts/_header.html.haml
.header-bar__row
  .left-header-bar__row.displayflex
    .header__logo          
      = link_to "PetMeeting", root_path, method: :get
    .header-navi
      = fa_icon 'paw', class: 'content-dark__icon'
      はじめに
    .header-navi-dropdown
      .header-navi-icon
        = fa_icon 'angle-double-down', class: 'header-first-dropdown__icon'
      .header-first-dropdown__item
      .header-first-dropdown__item
    .header-navi
      = fa_icon 'users', class: 'content-dark__icon'
      コミュニティ
    .header-navi-dropdown  
      .header-navi-icon
        = fa_icon 'angle-double-down', class: 'header-first-dropdown__icon'
      .header-first-dropdown__item
      .header-first-dropdown__item
        
  -# 詳細検索用
  -# .right-header-bar__row.displayflex
  -#   = search_form_for @search, url: articles_path do |f|
  -#     .right-bar-search.displayflex
  -#       .right-bar-search__keyword
  -#       %form.form
  -#       .keyword-search.displayflex
  -#         %input{type: "hidden"}/
  -#         .input-box
  -#           = fa_icon 'search', class: 'content-dark__icon'
  -#           = f.text_field :title_cont, placeholder: 'キーワードを入力' 
  -#           = hidden_field_tag :display_number, params[:display_number]
  -#         .input.submit-btn
  -#           = f.submit ("検索する")
  -#           %span 表示件数
  -#           = select_tag :display_number, options_for_select([10, 20, 50, 100, 500], params[:display_number]), :class => "form-control input-sm"
  -#           %span 件       
          

  .right-header-bar__row.displayflex
    = search_form_for @search, url: articles_path do |f|
      .right-bar-search.displayflex
        %form.form
        .keyword-search.displayflex
          .input-box
            = fa_icon 'search', class: 'content-dark__icon'
            = f.text_field :title_or_content_cont_all, placeholder: 'キーワードを入力', required: :true, class: 'header-search-text-area', maxlength: 20
            = f.submit ("検索") , class: 'headrer-search-btn'
            %span
                    
    - if user_signed_in?
      .user-info-list.displayflex      
        .user-info-list__like
          =link_to user_likes_path(current_user) do
            = fa_icon 'heart', class: 'content-dark__icon'
            いいね一覧
        .user-info-list__contribution
          = fa_icon 'sticky-note', class: 'content-dark__icon'
          = link_to "投稿する", new_article_path, method: :get
        .user-info-list__name  
          = fa_icon 'user', class: 'content-dark__icon'
          = current_user.name
          %ul.user-info-mypage
            %li.right__menu__list__hover-box
              =link_to user_path(current_user) do
                マイページ
            %li.right__menu__list__hover-box
              = link_to "ログアウト", destroy_user_session_path, method: :delete

    - else
      .right-header-login.displayflex
        .right-header-login__signin
          = link_to "ログイン", new_user_session_path, :class => 'post'
        .right-header-login__register
          = link_to "新規登録", entry_signup_signup_index_path, class: 'post'

          
.gretel-box
  = breadcrumbs separator: "＞"

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Articleapp
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = include_gon
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body.background
    = render 'layouts/notifications'
    .wrapper
      .header
        = render 'layouts/header'
      .main-body 
        .main-box.displayflex
          = yield 
      .footer